### PR TITLE
Add IsoFields and move interop.cljc to the correct location

### PR DESCRIPTION
**Pull request by unmonoqueteclea**
This PR add IsoFields and moves interopt.cljc to a (in my opinion) better location.

Tests from cljc.java-time are failing to me with cljs.java-time v1.14 with the following error:

`Syntax error (FileNotFoundException) compiling at (cljc/java_time/temporal/chrono_field.cljc:1:1).
Could not locate cljs/java_time/interop__init.class, cljs/java_time/interop.clj or cljs/java_time/interop.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.`

I am not sure if this PR will fix it.

### CODE REVIEW

**Comment by henryw374** [comment]
The interop ns has the name of this project. and it belongs in this project so i think that's the right place. 

the test is very hard to read with all the `(. ( . (. )` can you use threading macros or `(..)`

thanks

**Comment by henryw374** [comment]
also, it'd be great if you could check any other remaining classes java.time has which js-joda also has and add requires for those. I don't think there'd be many.

we don't really need any tests for them beyond knowing that they exist

**Comment by unmonoqueteclea** [comment]
Great, working on that! The tricky part for me is getting everything working in cljc.java-time. Maybe, in the meantime, you could check if you are also seeing the same error as me. 

Anyways, thank you for this super-useful library!

**Comment by unmonoqueteclea** [comment]
Ready again @henryw374

**Comment by henryw374** [comment]
cheers. released to clojars

**Pull request merged**
