### PR TITLE
Move protocols to java.time

### PR DESCRIPTION
**Pull request by joda**
Running '=' on the date/time classes didn't work unless a specific require on cljs.java-time.extend-eq-and-compare was added.

This is a problem when using this library from other libraries, since it's not obvious and/or easy to forget, and exposes internal details.

By including it in java.time, all consumers will get correct equality and hash functionality out of the box.

The cljs.java-time.extend-eq-and-compare namespace is emptied and kept for backward compatibility.

We found this when adding date/time stuff to [malli](https://github.com/metosin/malli), and it took a while to figure out why the tests didn't work.

If this is ok with you, it would be really nice with updates to [cljc.java-time](https://github.com/henryw374/cljc.java-time) and [tick](https://github.com/juxt/tick) as well.

### CODE REVIEW

**Comment by joda** [comment]
Just noticed that I forgot to update the README. I can fix that if it will be accepted

**Comment by henryw374** [comment]
Yes I'd accept this. 

Interesting re malli, because js-joda is somewhat chunky, but I guess it'll be an opt-in thing for malli users?

**Comment by joda** [comment]
Yeah, we don't know yet. For now we're working on integrating it into malli, but we might get rejected. If so, we need to figure out a nice way to keep it separate.

README is updated. Anything else you think I should change @henryw374 ?

**Comment by henryw374** [comment]
Thanks, I think this looks fine. 

Yeah I would say it should only be optional in Malli or any lib. Although js-joda is great in many situations, in others it's not right (because of size). Certainly I wouldn't want to find it pulled in when I didn't explicitly want it (size & currently extra steps to make it work on shadow) . hopefully the situation could improve, see https://github.com/henryw374/cljs.java-time/issues/3  anyway, that my 2c. I will approve and do a release

**Comment by joda** [comment]
Cool, thanks for the input!

**Pull request merged**
